version: '3'
  
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ./:/var/www/app
    ports:
      - 8000:8000
    depends_on:
      - mysql          
      
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  
volumes:
  db:
    driver: local
